services:
  hw-website:
    build:
      context: ./hw-website/
      args:
        - WWW_DATA_USER_ID=$UID
    container_name: hw-website
    ports:
      - ${WEB_PORT:-8080}:80
    volumes:
      - ../:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/public
